(define (mult a b)
  (define (double x)
    (* x 2))
  (define (halve x)
    (/ x 2))
  (define (mult-iter a b x)
    (cond ((= b 0) x)
          ((even? b) (mult-iter (double a) (- (halve b) 1) (+ x (double a))))
          (else (+ a (mult-iter a (- b 1) x)))))
  (mult-iter a b 0))