(define (sqrt x)
  (define (square x)
    (* x x))
  (define (good-enough? guess old-guess)
    (< (abs (- guess old-guess)) 0.001))
  (define (average x y)
    (/ (+ x y) 2))
  (define (improve guess old-guess)
    (average guess (/ x guess)))
  (define (sqrt-iter guess old-guess)
    (if (good-enough? guess old-guess)
        guess
        (sqrt-iter (improve guess old-guess) x)))
  (sqrt-iter 1.0 2.0))